kafkaPool: nav-dev
cpu: 100m
memory: 300Mi
external-host:
  - saf.dev-fss-pub.nais.io
  - dokarkiv.dev-fss-pub.nais.io
  - pdl-api.dev-fss-pub.nais.io
  - oppgave-q1.dev-fss-pub.nais.io
  - kodeverk.dev-fss-pub.nais.io
env:
  AIVEN_DOKUMENT_TOPIC: teamdokumenthandtering.aapen-dok-journalfoering-q1
    # SAF
  SAF_CLIENT_ID: dev-fss.teamdokumenthandtering.saf-q1
  SAF_URL: https://saf.dev-fss-pub.nais.io/graphql
    # Dokarkiv / JournlapostAPI
  DOKARKIV_CLIENT_ID: dev-fss.teamdokumenthandtering.dokarkiv-q1
  JOURNALPOSTAPI_URL: https://dokarkiv.dev-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
    # PDL
  PDL_CLIENT_ID: dev-fss.pdl.pdl-api
  PDL_URL: https://pdl-api.dev-fss-pub.nais.io/graphql
    # Oppgave
  OPPGAVE_CLIENT_ID: dev-fss.oppgavehandtering.oppgave-q1
  OPPGAVE_URL: https://oppgave-q1.dev-fss-pub.nais.io
    # Felleskodeverk
  FKV_URL: https://kodeverk.dev-fss-pub.nais.io/api/v1/kodeverk/Krutkoder/koder/betydninger?spraak=nb
