kafkaPool: nav-dev
cpu: 50m
memory: 600Mi
external-host:
  - saf.dev-fss-pub.nais.io
  - dokarkiv.dev-fss-pub.nais.io
  - pdl-api.dev-fss-pub.nais.io
  - oppgave-q1.dev-fss-pub.nais.io
  - kodeverk-api.nav.no
env:
  AIVEN_DOKUMENT_TOPIC: teamdokumenthandtering.aapen-dok-journalfoering-q1

  # SAF
  SAF_CLIENT_ID: dev-fss.teamdokumenthandtering.saf-q1
  SAF_URL: https://saf.dev-fss-pub.nais.io

  # Journalpost API (Dokarkiv)
  DOKARKIV_CLIENT_ID: dev-fss.teamdokumenthandtering.dokarkiv
  DOKARKIV_URL: https://dokarkiv.dev-fss-pub.nais.io

  # PDL
  PDL_CLIENT_ID: dev-fss.pdl.pdl-api
  PDL_URL: https://pdl-api.dev-fss-pub.nais.io

  # Gosys Oppgave
  OPPGAVE_CLIENT_ID: dev-fss.oppgavehandtering.oppgave-q1
  OPPGAVE_URL: https://oppgave-q1.dev-fss-pub.nais.io

  # Felles Kodeverk API
  KODEVERK_CLIENT_ID: dev-gcp.team-rocket.kodeverk-api
  KODEVERK_URL: https://kodeverk-api.nav.no
