apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-joark-mottak
  namespace: flex
  labels:
    team: flex
  annotations:
    config.linkerd.io/proxy-outbound-connect-timeout: 10s
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /internal/health/liveness
  readiness:
    path: /internal/health/readiness
  startup:
    path: /internal/health/liveness
    initialDelay: 20
  strategy:
    type: Recreate
  replicas:
    min: 1
    max: 1
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  kafka:
    pool: {{kafkaPool}}
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
  {{#each external-host}}
        - host: {{this}}
  {{/each}}
  env:
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}


