apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-joark-mottak
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  startup:
    path: /internal/alive
    initialDelay: 20
  strategy:
    type: Recreate
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  kafka:
    pool: {{kafkaPool}}
    streams: true
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
  {{#each external-host}}
        - host: {{this}}
  {{/each}}
  env:
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}


