kafkaPool: nav-prod
safHost: saf.prod-fss-pub.nais.io
dokarkivHost: dokarkiv.prod-fss-pub.nais.io
pdlHost: pdl-api.prod-fss-pub.nais.io
oppgaveHost: oppgave.prod-fss-pub.nais.io
flexFssProxyHost: flex-fss-proxy.prod-fss-pub.nais.io
env:
  AIVEN_DOKUMENT_TOPIC: teamdokumenthandtering.aapen-dok-journalfoering
    # SAF
  SAF_CLIENT_ID: feb9588b-a3d6-4d2f-8809-97284046ae72
  SAF_URL: https://saf.prod-fss-pub.nais.io/graphql
    # Dokarkiv / JournlapostAPI
  DOKARKIV_CLIENT_ID: prod-fss.teamdokumenthandtering.dokarkiv
  JOURNALPOSTAPI_URL: https://dokarkiv.prod-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
    # PDL
  PDL_CLIENT_ID: 5f3603e0-a590-4778-9d92-3ee220d95830
  PDL_URL: https://pdl-api.prod-fss-pub.nais.io/graphql
    # Oppgave
  OPPGAVE_CLIENT_ID: 50346823-61a0-49e7-ad89-ea2b1a0e90f8
  OPPGAVE_URL: https://oppgave.prod-fss-pub.nais.io
    # Felleskodeverk
  FLEX_FSS_PROXY_CLIENT_ID: prod-fss.flex.flex-fss-proxy
  FKV_URL: https://flex-fss-proxy.prod-fss-pub.nais.io/api/v1/kodeverk/Krutkoder/koder/betydninger?spraak=nb
