kafkaPool: nav-prod
cpu: 50m
memory: 800Mi
external-host:
  - saf.prod-fss-pub.nais.io
  - dokarkiv.prod-fss-pub.nais.io
  - pdl-api.prod-fss-pub.nais.io
  - oppgave.prod-fss-pub.nais.io
  - kodeverk-api.nav.no
env:
  AIVEN_DOKUMENT_TOPIC: teamdokumenthandtering.aapen-dok-journalfoering

  # SAF
  SAF_CLIENT_ID: prod-fss.teamdokumenthandtering.saf
  SAF_URL: https://saf.prod-fss-pub.nais.io

  # Journalpost API (Dokarkiv)
  DOKARKIV_CLIENT_ID: prod-fss.teamdokumenthandtering.dokarkiv
  DOKARKIV_URL: https://dokarkiv.prod-fss-pub.nais.io

  # PDL
  PDL_CLIENT_ID: prod-fss.pdl.pdl-api
  PDL_URL: https://pdl-api.prod-fss-pub.nais.io

  # Gosys Oppgave
  OPPGAVE_CLIENT_ID: 50346823-61a0-49e7-ad89-ea2b1a0e90f8
  OPPGAVE_URL: https://oppgave.prod-fss-pub.nais.io

  # Felles Kodeverk API
  KODEVERK_CLIENT_ID: prod-gcp.team-rocket.kodeverk-api
  KODEVERK_URL: https://kodeverk-api.nav.no


