apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-joark-mottak
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: internal/alive
    initialDelay: 20
  readiness:
    path: internal/ready
    initialDelay: 20
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: internal/metrics
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  kafka:
    pool: nav-dev
    streams: true
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: "saf.dev-fss-pub.nais.io"
        - host: "dokarkiv.dev-fss-pub.nais.io"
        - host: "pdl-api.dev-fss-pub.nais.io"
        - host: "oppgave-q1.dev-fss-pub.nais.io"
        - host: "flex-fss-proxy.dev-fss-pub.nais.io"
  env:
    - name: AIVEN_DOKUMENT_TOPIC
      value: teamdokumenthandtering.aapen-dok-journalfoering-q1
    # SAF
    - name: SAF_CLIENT_ID
      value: dev-fss.teamdokumenthandtering.saf
    - name: SAF_URL
      value: https://saf.dev-fss-pub.nais.io/graphql
    # Dokarkiv / JournlapostAPI
    - name: DOKARKIV_CLIENT_ID
      value: 972814f3-8bdf-44f8-a191-c2ed00020b54
    - name: JOURNALPOSTAPI_URL
      value: https://dokarkiv.dev-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
    # PDL
    - name: PDL_CLIENT_ID
      value: dev-fss.pdl.pdl-api
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    # Oppgave
    - name: OPPGAVE_CLIENT_ID
      value: dev-fss.oppgavehandtering.oppgave-q1
    - name: OPPGAVE_URL
      value: https://oppgave-q1.dev-fss-pub.nais.io
    # Felleskodeverk
    - name: FLEX_FSS_PROXY_CLIENT_ID
      value: dev-fss.flex.flex-fss-proxy
    - name: FKV_URL
      value: https://flex-fss-proxy.dev-fss-pub.nais.io/api/v1/kodeverk/Krutkoder/koder/betydninger
